const CONFIG={ADMIN_EMAIL:'topcuyusuf254@gmail.com',SHEET_NAME:'İonenSpiegel Topluluk Verileri'};
const NEWS_FEEDS=[
 {name:'ASpor',url:'https://www.aspor.com.tr/rss/futbol.xml'},
 {name:'ASpor Süper Lig',url:'https://www.aspor.com.tr/rss/spor-toto-super-lig.xml'},
 {name:'Habertürk Spor',url:'https://www.haberturk.com/rss/spor.xml'},
 {name:'A Haber Spor',url:'https://www.ahaber.com.tr/rss/spor.xml'}
];

function getAdminEmail_(){return CONFIG.ADMIN_EMAIL;}
function getSheet_(){const p=PropertiesService.getScriptProperties();let id=p.getProperty('SHEET_ID');if(id)return SpreadsheetApp.openById(id).getSheets()[0];const ss=SpreadsheetApp.create(CONFIG.SHEET_NAME),sh=ss.getSheets()[0];sh.setName('Veriler');sh.appendRow(['Tarih','Tür','Ad','Yorum','Seçim']);p.setProperty('SHEET_ID',ss.getId());return sh;}
function clean_(s){return String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/\s+/g,' ').trim();}
function getChild_(e,n){let x=e.getChild(n);if(!x)x=e.getChild(n,e.getNamespace());return x?clean_(x.getText()):'';}
function parseFeed_(xml,source){const d=XmlService.parse(xml),r=d.getRootElement(),ch=r.getChild('channel');const arr=ch?ch.getChildren('item'):r.getChildren('entry',r.getNamespace()),out=[];arr.forEach(i=>{const title=getChild_(i,'title'),desc=getChild_(i,'description')||getChild_(i,'summary')||getChild_(i,'content');let link=getChild_(i,'link');if(!link){const l=i.getChild('link',i.getNamespace());if(l){const a=l.getAttribute('href');link=a?a.getValue():l.getText();}}const date=getChild_(i,'pubDate')||getChild_(i,'published')||getChild_(i,'updated');if(title&&link)out.push({title:title.slice(0,220),description:(desc||'Güncel futbol haberi.').slice(0,320),source:source,link:link,pubDate:date,category:'FUTBOL'});});return out;}
function getNews_(){let all=[];NEWS_FEEDS.forEach(f=>{try{const r=UrlFetchApp.fetch(f.url,{muteHttpExceptions:true,followRedirects:true,headers:{'User-Agent':'Mozilla/5.0'}});if(r.getResponseCode()>=200&&r.getResponseCode()<300)all=all.concat(parseFeed_(r.getContentText(),f.name));}catch(e){Logger.log(f.name+' '+e);}});const seen={};return all.filter(n=>{const k=n.link||n.title;if(seen[k])return false;seen[k]=1;return true;}).slice(0,40);}
function doGet(e){const cb=String((e&&e.parameter&&e.parameter.callback)||''),sh=getSheet_(),v=sh.getDataRange().getValues(),comments=[],votes={'0':0,'1':0,'2':0,'3':0},p=PropertiesService.getScriptProperties();for(let i=1;i<v.length;i++){const r=v[i],t=String(r[1]||'');if(t==='yorum')comments.push({name:String(r[2]||'Ziyaretçi'),text:String(r[3]||''),date:r[0] instanceof Date?r[0].toLocaleString('tr-TR'):String(r[0]||'')});if(t==='anket'){const c=String(r[4]||'');if(Object.prototype.hasOwnProperty.call(votes,c))votes[c]++;}}comments.reverse();comments.splice(50);const result={ok:true,comments,votes,visitors:{total:Number(p.getProperty('VISITOR_TOTAL')||0),today:Number(p.getProperty('VISITOR_TODAY')||0)},items:getNews_(),updatedAt:new Date().toISOString()};const json=JSON.stringify(result);if(cb&&/^[A-Za-z_$][\w$\.]*$/.test(cb))return ContentService.createTextOutput(cb+'('+json+')').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON);}
function doPost(e){try{const p=(e&&e.parameter)||{},a=String(p.action||''),sh=getSheet_();if(a==='ziyaret'){const l=LockService.getScriptLock();l.waitLock(5000);try{const q=PropertiesService.getScriptProperties(),k=Utilities.formatDate(new Date(),Session.getScriptTimeZone(),'yyyy-MM-dd');let total=Number(q.getProperty('VISITOR_TOTAL')||0)+1,today=Number(q.getProperty('VISITOR_TODAY')||0);if(q.getProperty('VISITOR_TODAY_KEY')!==k)today=0;today++;q.setProperties({VISITOR_TOTAL:String(total),VISITOR_TODAY:String(today),VISITOR_TODAY_KEY:k});}finally{l.releaseLock();}return reply_({ok:true});}if(a==='yorum'){const n=String(p.name||'').trim().slice(0,60),t=String(p.text||'').trim().slice(0,1000);if(!n||!t)return reply_({ok:false,error:'Ad ve yorum gerekli.'});sh.appendRow([new Date(),'yorum',n,t,'']);MailApp.sendEmail({to:getAdminEmail_(),subject:'İonenSpiegel: Yeni yorum',htmlBody:'<h2>Yeni İonenSpiegel yorumu</h2><p><b>Ad:</b> '+esc_(n)+'</p><p><b>Yorum:</b><br>'+esc_(t).replace(/\n/g,'<br>')+'</p>'});return reply_({ok:true});}if(a==='anket'){const c=String(p.choice||'');if(!/^[0-3]$/.test(c))return reply_({ok:false,error:'Geçersiz seçim.'});sh.appendRow([new Date(),'anket','','',c]);const labels=['Victor Osimhen','Orkun Kökçü','Fred','Thomas Müller'];MailApp.sendEmail({to:getAdminEmail_(),subject:'İonenSpiegel: Yeni anket oyu',htmlBody:'<h2>Yeni anket oyu</h2><p><b>Seçim:</b> '+esc_(labels[Number(c)])+'</p>'});return reply_({ok:true});}return reply_({ok:false,error:'Bilinmeyen işlem.'});}catch(e){return reply_({ok:false,error:String(e)});}}
function reply_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON);}
function esc_(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');}
